const carData = {
    "Blue Falcon": {
        "name": "Blue Falcon",
        "id": 0,
        "acceleration": ".005",
        "top speed": 1.034,
        "max_boost_velocity": 1.551,
        "handling": .25,
        "boost": 4,
        "body": 80,
        "sprite": "Sprites/Cars/bluefalcon.png"
    },
    "Astro Robin": {
        "name": "Astro Robin",
        "id": 14,
        "acceleration": ".008",
        "top speed": 1.025,
        "max_boost_velocity": 1.5375,
        "handling": .15,
        "boost": 4,
        "body": 80,
        "sprite": "Sprites/Cars/astrorobin.png"
    },
    "Big Fang": {
        "name": "Big Fang",
        "id": 15,
        "acceleration": ".003",
        "top speed": 1.106,
        "max_boost_velocity": 1.659,
        "handling": .15,
        "boost": 7.5,
        "body": 80,
        "sprite": "Sprites/Cars/bigfang.png",
        "left": 0,
        "default": 64,
        "right": 144
    },
    "Black Shadow": {
        "name": "Black Shadow",
        "id": 30,
        "acceleration": ".003",
        "top speed": 1.129,
        "max_boost_velocity": 1.6935,
        "handling": .2,
        "boost": 6,
        "body": 85,
        "sprite": "Sprites/Cars/blackshadow.png"
    },
    "Blood Hawk": {
        "name": "Blood Hawk",
        "id": 25,
        "acceleration": ".006",
        "top speed": 1.008,
        "max_boost_velocity": 1.512,
        "handling": .1,
        "boost": 4,
        "body": 80,
        "sprite": "Sprites/Cars/bloodhawk.png"
    },
    "Crazy Bear": {
        "name": "Crazy Bear",
        "id": 29,
        "acceleration": ".007",
        "top speed": 1.014,
        "max_boost_velocity": 1.521,
        "handling": .1,
        "boost": 3,
        "body": 107,
        "sprite": "Sprites/Cars/crazybear.png"
    },
    "Death Anchor": {
        "name": "Death Anchor",
        "id": 13,
        "acceleration": ".004",
        "top speed": 1.118,
        "max_boost_velocity": 1.677,
        "handling": .1,
        "boost": 3,
        "body": 75,
        "sprite": "Sprites/Cars/deathanchor.png"
    },
    "Deep Claw": {
        "name": "Deep Claw",
        "id": 8,
        "acceleration": ".004",
        "top speed": 1.035,
        "max_boost_velocity": 1.5525,
        "handling": .2,
        "boost": 6,
        "body": 80,
        "sprite": "Sprites/Cars/deepclaw.png"
    },
    "Dragon Bird": {
        "name": "Dragon Bird",
        "id": 0,
        "acceleration": ".005",
        "top speed": 1.059,
        "max_boost_velocity": 1.5885,
        "handling": .2,
        "boost": 6,
        "body": 80,
        "sprite": "Sprites/Cars/dragonbird.png"
    },
    "Elegance Liberty": {
        "name": "Elegance Liberty",
        "id": 19,
        "acceleration": ".003",
        "top speed": 1.051,
        "max_boost_velocity": 1.5765,
        "handling": .2,
        "boost": 6,
        "body": 75,
        "sprite": "Sprites/Cars/eleganceliberty.png"
    },
    "Fire Stingray": {
        "name": "Fire Stingray",
        "id": 5,
        "acceleration": ".003",
        "top speed": 1.096,
        "max_boost_velocity": 1.644,
        "handling": .25,
        "boost": 6,
        "body": 85,
        "sprite": "Sprites/Cars/firestingray.png"
    },
    "Golden Fox": {
        "name": "Golden Fox",
        "id": 3,
        "acceleration": ".004",
        "top speed": 1.017,
        "max_boost_velocity": 1.5255,
        "handling": .15,
        "boost": 4,
        "body": 75,
        "sprite": "Sprites/Cars/goldenfox.png"
    },
    "Great Star": {
        "name": "Great Star",
        "id": 9,
        "acceleration": ".007",
        "top speed": 1.018,
        "max_boost_velocity": 1.527,
        "handling": .1,
        "boost": 3,
        "body": 75,
        "sprite": "Sprites/Cars/greatstar.png"
    },
    "Green Panther": {
        "name": "Green Panther",
        "id": 17,
        "acceleration": ".007",
        "top speed": 1.021,
        "max_boost_velocity": 1.5315,
        "handling": .1,
        "boost": 4,
        "body": 120,
        "sprite": "Sprites/Cars/greenpanther.png"
    },
    "Hyper Speeder": {
        "name": "Hyper Speeder",
        "id": 18,
        "acceleration": ".003",
        "top speed": 1.111,
        "max_boost_velocity": 1.6665,
        "handling": .25,
        "boost": 4,
        "body": 80,
        "sprite": "Sprites/Cars/hyperspeeder.png"
    },
    "Iron Tiger": {
        "name": "Iron Tiger",
        "id": 4,
        "acceleration": ".004",
        "top speed": 1.052,
        "max_boost_velocity": 1.578,
        "handling": .2,
        "boost": 5,
        "body": 85,
        "sprite": "Sprites/Cars/irontiger.png"
    },
    "King Meteor": {
        "name": "King Meteor",
        "id": 20,
        "acceleration": ".005",
        "top speed": 1.022,
        "max_boost_velocity": 1.533,
        "handling": .1,
        "boost": 4,
        "body": 75,
        "sprite": "Sprites/Cars/kingmeteor.png"
    },
    "Lambo": {
        "name": "Blue Falcon",
        "id": 0,
        "acceleration": ".005",
        "top speed": 1.034,
        "max_boost_velocity": 1.551,
        "handling": .25,
        "boost": 4,
        "body": 80,
        "sprite": "Sprites/Cars/lambo.png"
    },
    "Little Wyvern": {
        "name": "Little Wyvern",
        "id": 10,
        "acceleration": ".005",
        "top speed": 1.044,
        "max_boost_velocity": 1.566,
        "handling": .15,
        "boost": 5,
        "body": 75,
        "sprite": "Sprites/Cars/littlewyvern.png"
    },
    "Mad Wolf": {
        "name": "Mad Wolf",
        "id": 11,
        "acceleration": ".005",
        "top speed": 1.054,
        "max_boost_velocity": 1.581,
        "handling": .05,
        "boost": 5,
        "body": 85,
        "sprite": "Sprites/Cars/madwolf.png"
    },
    "Mighty Hurricane": {
        "name": "Mighty Hurricane",
        "id": 28,
        "acceleration": ".006",
        "top speed": 1.057,
        "max_boost_velocity": 1.5855,
        "handling": .2,
        "boost": 5,
        "body": 75,
        "sprite": "Sprites/Cars/mightyhurricane.png"
    },
    "Mighty Typhoon": {
        "name": "Mighty Typhoon",
        "id": 27,
        "acceleration": ".006",
        "top speed": 1.039,
        "max_boost_velocity": 1.5585,
        "handling": .25,
        "boost": 6,
        "body": 75,
        "sprite": "Sprites/Cars/mightytyphoon.png"
    },
    "Moon Shadow": {
        "name": "Moon Shadow",
        "id": 36,
        "acceleration": ".005",
        "top speed": 1.024,
        "max_boost_velocity": 1.536,
        "handling": .2,
        "boost": 5,
        "body": 80,
        "sprite": "Sprites/Cars/moonshadow.png"
    },
    "Night Thunder": {
        "name": "Night Thunder",
        "id": 23,
        "acceleration": ".007",
        "top speed": 1.016,
        "max_boost_velocity": 1.524,
        "handling": .05,
        "boost": 3,
        "body": 75,
        "sprite": "Sprites/Cars/nightthunder.png"
    },
    "Panzer Emerald": {
        "name": "Panzer Emerald",
        "id": 38,
        "acceleration": ".003",
        "top speed": 1.025,
        "max_boost_velocity": 1.5375,
        "handling": .2,
        "boost": 5,
        "body": 80,
        "sprite": "Sprites/Cars/panzeremerald.png"
    },
    "Queen Meteor": {
        "name": "Queen Meteor",
        "id": 21,
        "acceleration": ".006",
        "top speed": 1.038,
        "max_boost_velocity": 1.557,
        "handling": .1,
        "boost": 4,
        "body": 75,
        "sprite": "Sprites/Cars/queenmeteor.png"
    },
    "Red Gazelle": {
        "name": "Red Gazelle",
        "id": 1,
        "acceleration": ".004",
        "top speed": 1.038,
        "max_boost_velocity": 1.557,
        "handling": .2,
        "boost": 3,
        "body": 75,
        "sprite": "Sprites/Cars/redgazelle.png"
    },
    "Sonic Phantom": {
        "name": "Sonic Phantom",
        "id": 16,
        "acceleration": ".005",
        "top speed": 1.106,
        "max_boost_velocity": 1.659,
        "handling": .2,
        "boost": 3,
        "body": 75,
        "sprite": "Sprites/Cars/sonicphantom.png"
    },
    "Space Angler": {
        "name": "Space Angler",
        "id": 19,
        "acceleration": ".003",
        "top speed": 1.051,
        "max_boost_velocity": 1.5765,
        "handling": .2,
        "boost": 6,
        "body": 75,
        "sprite": "Sprites/Cars/spaceangler.png"
    },
    "Super Piranha": {
        "name": "Super Piranha",
        "id": 12,
        "acceleration": ".005",
        "top speed": 1.024,
        "max_boost_velocity": 1.536,
        "handling": .1,
        "boost": 5,
        "body": 80,
        "sprite": "Sprites/Cars/superpiranha.png"
    },
    "Twin Noritta": {
        "name": "Twin Noritta",
        "id": 22,
        "acceleration": ".007",
        "top speed": 1.017,
        "max_boost_velocity": 1.5255,
        "handling": .15,
        "boost": 3,
        "body": 75,
        "sprite": "Sprites/Cars/twinnoritta.png"
    },
    "White Cat": {
        "name": "White Cat",
        "id": 2,
        "acceleration": ".005",
        "top speed": 1.042,
        "max_boost_velocity": 1.563,
        "handling": .1,
        "boost": 4,
        "body": 75,
        "sprite": "Sprites/Cars/whitecat.png"
    },
    "Wild Boar": {
        "name": "Wild Boar",
        "id": 24,
        "acceleration": ".003",
        "top speed": 1.112,
        "max_boost_velocity": 1.668,
        "handling": .15,
        "boost": 5,
        "body": 85,
        "sprite": "Sprites/Cars/wildboar.png"
    },
    "Wild Goose": {
        "name": "Wild Goose",
        "id": 6,
        "acceleration": ".004",
        "top speed": 1.048,
        "max_boost_velocity": 1.572,
        "handling": .05,
        "boost": 8,
        "body": 160,
        "sprite": "Sprites/Cars/wildgoose.png"
    },
    "Wonder Wasp": {
        "name": "Wonder Wasp",
        "id": 26,
        "acceleration": ".006",
        "top speed": 1.034,
        "max_boost_velocity": 1.551,
        "handling": .2,
        "boost": 5,
        "body": 75,
        "sprite": "Sprites/Cars/wonderwasp.png"
    },
}