const trackData = {
    "Digital Violet": {
        "name": "Digital Violet",
        "starting_x": 140.98064874052415,
        "starting_y": 14.980766027134674,
        "theta": (3*Math.PI)/2,
        "cp_x": 319,
        "cp_y": 197,
        "finish_x": 143,
        "finish_y": 5,
        "trackSprite": "Sprites/Tracks/edited track.png",
        "skySprite": "Sprites/Tracks/sky.webp",
        "hiddenTrackSprite": "Sprites/Tracks/whiteland_hidden.png",
        "shrunkSprite" : "Sprites/Tracks/track shrunk.png"
    },
    "Prismatic Passage": {
        "name": "Prismatic Passage",
        "starting_x": 140.98064874052415,
        "starting_y": 14.980766027134674,
        "theta": (3 * Math.PI)/2,
        "cp_x": 319,
        "cp_y": 252,
        "finish_x": 143,
        "finish_y": 5,
        "trackSprite": "Sprites/Tracks/rainbow.png",
        "skySprite": "Sprites/Tracks/stars.webp",
        "hiddenTrackSprite": "Sprites/Tracks/hidden_rainbow.png",
        "shrunkSprite" : "Sprites/Tracks/rainbow.png"
    },
    "Atlantis": {
        "name": "Atlantis",
        "starting_x": 494,
        "starting_y": 461,
        "theta": (3 * Math.PI)/2,
        "cp_x": 150,
        "cp_y": 100,
        "finish_x": 496,
        "finish_y": 452,
        "trackSprite": "Sprites/Tracks/sandocean.png",
        "skySprite": "Sprites/Tracks/underwater.png",
        "hiddenTrackSprite": "Sprites/Tracks/sandocean_hidden.png",
        "shrunkSprite" : "Sprites/Tracks/sandocean_shrunk.png"
    },
    "Raging Inferno": {
        "name": "Raging Inferno",
        "starting_x": 280,
        "starting_y": 80,
        "theta": (3 * Math.PI)/2,
        "cp_x": 663,
        "cp_y": 306,
        "finish_x": 281,
        "finish_y": 69,
        "trackSprite": "Sprites/Tracks/redLava.png",
        "skySprite": "Sprites/Tracks/hotSky.webp",
        "hiddenTrackSprite": "Sprites/Tracks/redLava_hidden.png",
        "shrunkSprite" : "Sprites/Tracks/redLava_shrunk.png"
    },
    "Mute City 2": {
        "name": "Mute City 2",
        "starting_x": 274,
        "starting_y": 45,
        "theta": (Math.PI)/2,
        "cp_x": 740,
        "cp_y": 355,
        "finish_x": 270,
        "finish_y": 40,
        "trackSprite": "Sprites/Tracks/mutecity2.png",
        "skySprite": "Sprites/Tracks/mutecity2bg.png",
        "hiddenTrackSprite": "Sprites/Tracks/mutecity2_hidden.png",
        "shrunkSprite" : "Sprites/Tracks/mutecity2_shrunk.png"
    },
    "Big Blue": {
        "name": "Big Blue",
        "starting_x": 274,
        "starting_y": 78,
        "theta": (Math.PI)/2,
        "cp_x": 474,
        "cp_y": 155,
        "finish_x": 273,
        "finish_y": 68,
        "trackSprite": "Sprites/Tracks/bigBlue.png",
        "skySprite": "Sprites/Tracks/bigBlueBG.png",
        "hiddenTrackSprite": "Sprites/Tracks/bigBlue_hidden.png",
        "shrunkSprite" : "Sprites/Tracks/bigBlue_shrunk.png"
    },
    "Port Town": {
        "name": "Port Town",
        "starting_x": 396,
        "starting_y": 78,
        "theta": (3* Math.PI)/2,
        "cp_x": 444,
        "cp_y": 175,
        "finish_x": 397,
        "finish_y": 68,
        "trackSprite": "Sprites/Tracks/porttown.png",
        "skySprite": "Sprites/Tracks/porttownbg.png",
        "hiddenTrackSprite": "Sprites/Tracks/porttown_hidden.png",
        "shrunkSprite" : "Sprites/Tracks/porttown_shrunk.png"
    },
    "Red Canyon": {
        "name": "Red Canyon",
        "starting_x": 458,
        "starting_y": 65,
        "theta": (3* Math.PI)/2,
        "cp_x": 853,
        "cp_y": 400,
        "finish_x": 459,
        "finish_y": 54,
        "trackSprite": "Sprites/Tracks/redcanyon.png",
        "skySprite": "Sprites/Tracks/redcanyonbg.png",
        "hiddenTrackSprite": "Sprites/Tracks/redcanyon_hidden.png",
        "shrunkSprite" : "Sprites/Tracks/redcanyon_shrunk.png"
    },
    "Deathwind": {
        "name": "Deathwind",
        "starting_x": 467,
        "starting_y": 95,
        "theta": (3* Math.PI)/2,
        "cp_x": 530,
        "cp_y": 285,
        "finish_x": 468,
        "finish_y": 83,
        "trackSprite": "Sprites/Tracks/deathwind.png",
        "skySprite": "Sprites/Tracks/deathwindbg.png",
        "hiddenTrackSprite": "Sprites/Tracks/deathwind_hidden.png",
        "shrunkSprite" : "Sprites/Tracks/deathwind_shrunk.png"
    }
}